# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53490f0f3251c935257b36b8cc75b1d228954f1d4a83fdd388112c5a0e92351856581c762964b55df6986aa0b7343161ee62e41ec6e3fde173d19a5c6bf0409c

test:
  secret_key_base: d211d69c77a6999b1dcc624c946b6180348c8c158f7e89efc1e440066e766c98becd35e644ac0dc9a856ce105de06e7806da72d12ee7e35b35276a92fa511620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
